// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnl2NoKmDoTp7LBr-iYdX78zUD9h5lWoI',
    appId: '1:108555357298:web:8b8540bb553d1b305ec6eb',
    messagingSenderId: '108555357298',
    projectId: 'elaaj-authentication',
    authDomain: 'elaaj-authentication.firebaseapp.com',
    storageBucket: 'elaaj-authentication.appspot.com',
    measurementId: 'G-KGL6Q2ZCHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqHZ6FvlNKZJtqoo-ITYesnkbygFMLiAc',
    appId: '1:108555357298:android:6a9546356a123c285ec6eb',
    messagingSenderId: '108555357298',
    projectId: 'elaaj-authentication',
    storageBucket: 'elaaj-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdepypPHLpxFr3B5hXhCsQmt4kIC23AMA',
    appId: '1:108555357298:ios:3641d0c69a5d9fbc5ec6eb',
    messagingSenderId: '108555357298',
    projectId: 'elaaj-authentication',
    storageBucket: 'elaaj-authentication.appspot.com',
    androidClientId: '108555357298-9us67c935jqji9gths0qe7v7s0h91c35.apps.googleusercontent.com',
    iosClientId: '108555357298-3bd5b5a0l407ue12dtduubc06iad90s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.elaajapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdepypPHLpxFr3B5hXhCsQmt4kIC23AMA',
    appId: '1:108555357298:ios:3641d0c69a5d9fbc5ec6eb',
    messagingSenderId: '108555357298',
    projectId: 'elaaj-authentication',
    storageBucket: 'elaaj-authentication.appspot.com',
    androidClientId: '108555357298-9us67c935jqji9gths0qe7v7s0h91c35.apps.googleusercontent.com',
    iosClientId: '108555357298-3bd5b5a0l407ue12dtduubc06iad90s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.elaajapp',
  );
}
