// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqp03xds5Y_hI7Q-7upWANcF-Ogdg4uhQ',
    appId: '1:148486910775:web:714f89bd966c9cd9d260b2',
    messagingSenderId: '148486910775',
    projectId: 'elaaj-b8c1e',
    authDomain: 'elaaj-b8c1e.firebaseapp.com',
    storageBucket: 'elaaj-b8c1e.appspot.com',
    measurementId: 'G-DHLQLH8HQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGU2-kG5w1EjuRj2RsNsdAmMVcacey8bM',
    appId: '1:148486910775:android:0e1ad35fb0c3ad15d260b2',
    messagingSenderId: '148486910775',
    projectId: 'elaaj-b8c1e',
    storageBucket: 'elaaj-b8c1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn8d6mWzeINXyvaKBlZrFXj5gO4uSqtBE',
    appId: '1:148486910775:ios:e2ebb19eb47c3b13d260b2',
    messagingSenderId: '148486910775',
    projectId: 'elaaj-b8c1e',
    storageBucket: 'elaaj-b8c1e.appspot.com',
    iosClientId: '148486910775-0ljeb4fbn0dq0nf7g8ms7nbhosgo6rs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.elaajapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn8d6mWzeINXyvaKBlZrFXj5gO4uSqtBE',
    appId: '1:148486910775:ios:e2ebb19eb47c3b13d260b2',
    messagingSenderId: '148486910775',
    projectId: 'elaaj-b8c1e',
    storageBucket: 'elaaj-b8c1e.appspot.com',
    iosClientId: '148486910775-0ljeb4fbn0dq0nf7g8ms7nbhosgo6rs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.elaajapp',
  );
}
